---
orbs:
  slack: circleci/slack@3.3.0

version: 2.1

executors:
  ruby:
    parameters:
      tag:
        type: string
        default: "latest"
    docker:
      - image: circleci/ruby:<< parameters.tag >>

commands:
  hello_command:
    description: "Hello command"
    steps:
      -
        run:
          name: "hello step 1"
          command: |
            echo "HELLO WORLD"
  slack_test:
    description: "Slack test"
    steps:
      -
        run:
          name: "変数に代入してみる"
          command: MESSAGE=`echo "HELLO"`
      -
        slack/notify:
          color: success
          message: ${MESSAGE}

jobs:
  hello_job:
    executor: ruby
    steps:
      - hello_command
  slack_test:
    executor: ruby
    steps:
      - checkout
      - slack_test

workflows:
  version: 2.1
  build:
    jobs:
      - hello_job
      - slack_test
  schedule_workflow:
    triggers:
      -
        schedule:
          cron: "* 19 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - hello_job
