---
orbs:
  slack: circleci/slack@3.3.0

version: 2.1

executors:
  ruby:
    parameters:
      tag:
        type: string
        default: "latest"
    docker:
      - image: circleci/ruby:<< parameters.tag >>

commands:
  hello_command:
    description: "Hello command"
    steps:
      -
        run:
          name: "ls test"
          command: ls -a
      -
        run:
          name: "hello step"
          command: |
            echo "HELLO WORLD"
  slack_awscost:
    description: "AWSのコストをSlackへ通知"
    steps:
      -
        run:
          name: "もう一度変数に代入"
          command: export MY_ENV="testtesttest"
      -
        run:
          name: "もう一度変数に代入"
          command: hoge="testtesttest"
      -
        slack/notify:
          color: success
          message: ${hoge}
      -
        slack/notify:
          color: success
          message: ${MY_ENV}
      -
        slack/notify:
          color: success
          message: "`ls -a ./`, `pwd`"
      -
        slack/notify:
          color: success
          message: "`ruby aws-cost.rb`"

jobs:
  hello_job:
    executor: ruby
    steps:
      - checkout
      - hello_command
  slack_awscost:
    executor: ruby
    steps:
      - checkout
      - slack_awscost

workflows:
  version: 2.1
  build:
    jobs:
      - slack_awscost
#      - hello_job
  schedule_workflow:
    triggers:
      -
        schedule:
          cron: "* 19 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - hello_job
