---
orbs:
  slack: circleci/slack@3.3.0

version: 2.1

executors:
  ruby:
    parameters:
      tag:
        type: string
        default: "latest"
    docker:
      - image: circleci/ruby:<< parameters.tag >>

commands:
  hello_command:
    description: "Hello command"
    steps:
      -
        run:
          name: "ls test"
          command: ls -a
      -
        run:
          name: "hello step"
          command: |
            echo "HELLO WORLD"
  slack_awscost:
    description: "AWSのコストをSlackへ通知"
    steps:
      -
        run:
          name: "bundle install"
          command: bundle install
      -
        slack/notify:
          color: success
          message: "`ruby aws.rb`"

jobs:
  hello_job:
    executor: ruby
    steps:
      - checkout
      - hello_command
  slack_awscost:
    executor: ruby
    steps:
      - checkout
      - slack_awscost

workflows:
  version: 2.1
  build:
    jobs:
      - slack_awscost
#      - hello_job
  schedule_workflow:
    triggers:
      -
        schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - slack_awscost
