---
version: 2.1

executors:
  ruby:
    parameters:
      tag:
        type: string
        default: "latest"
    docker:
      - image: circleci/ruby:<< parameters.tag >>

commands:
  hello_command:
    description: "Hello command"
    steps:
      -
        run:
          name: "hello step 1"
          command: |
            echo "HELLO WORLD"

jobs:
  hello_job:
    executor: ruby
    steps:
      - checkout
      - hello_command

workflows:
  version: 2.1
  build:
    jobs:
      - hello_job
  schedule_workflow:
    triggers:
      -
        schedule:
          cron: "5 * * * *"
    jobs:
      - hello_job
      - hello_job
      - hello_job
      - hello_job
