name: Hello, World!
on: push

jobs:
  build:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
      - run: echo "Hello, World!"
      - run: echo "Hello, World!"
      - run: echo "Hello, World!"
      - run: echo ${{ secrets.GITHUB_TOKEN }}
      - run: echo ${{ secrets.MY_HIMITSU }}
      - run: echo ${{ secrets.MY_HIMITSU_TOKANAI }}
